plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: |
        poetry version ${nextRelease.version}
        sed -i "s/^__version__ = ".*"/__version__ = "${nextRelease.version}"/" youtube_playlist_randomizer/__init__.py
  - - "@semantic-release/git"
    - assets:
        - pyproject.toml
        - youtube_playlist_randomizer/__init__.py
        - CHANGELOG.md
  - "@semantic-release/github"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
