name: CD

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v4.2.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build --username __token__ --password $POETRY_PYPI_TOKEN