name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - run: go mod download
      - run: go vet -tags "sqlite_fts5" ./...
      - run: go test -tags "sqlite_fts5" -v ./...
  otel:
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v4
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          otelToken: ${{ secrets.OTEL_TOKEN }}
