name: Renovate
on:
  schedule:
    - cron: '0 8 * * *' # 09:00 UTC+1
    - cron: '0 11 * * *' # 12:00 UTC+1
    - cron: '0 14 * * *' # 15:00 UTC+1
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c # v46.2.5
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
  otel:
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [renovate]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@895874bfae14f840e3032f1a14c3f2b45c93f4af # v4.1.1
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
